name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install tree
      run: sudo apt -y update && sudo apt -y install tree
    - name: tree
      run: tree
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: tree
      run: tree
